### ISSUE TITLE
Can't print empty AST

### ISSUE THREAD

**Issue by Flaise** [benjamn/recast#220]
This isn't a big deal when doing stuff manually but it's one more unnecessary edge case for utility/library writers to be aware of:

    $ node
    > var recast = require('recast')
    undefined
    > recast.print(recast.parse(''))
    AssertionError: no line 0 (line numbers start from 1)
        at Lines.Lp.getIndentAt (.../node_modules/recast/lib/lines.js:387:12)
        at Lines.Lp.getLineLength (.../node_modules/recast/lib/lines.js:459:17)
        at Lines.Lp.nextPos (.../node_modules/recast/lib/lines.js:466:18)
        at Lines.Lp.skipSpaces (.../node_modules/recast/lib/lines.js:546:23)
        at Object.exports.getTrueLoc (.../node_modules/recast/lib/util.js:117:22)
        at Object.parse (.../node_modules/recast/lib/parser.js:49:31)
        at repl:1:21
        at REPLServer.defaultEval (repl.js:164:27)
        at bound (domain.js:250:14)
        at REPLServer.runBound [as eval] (domain.js:263:12)

Node 4.1.1
NPM 3.3.5
Recast 0.10.34
Ubuntu 14.04

**Comment by impinball** [comment]
Found as well

**Comment by aft-luke** [comment]
So this is a bug inside esprima?
