### ISSUE TITLE
ES7 Property Initializers not work

### ISSUE THREAD

**Issue by noyobo** [benjamn/recast#300]
```
var code = `
class App extends Component {
  static defaultProps = { hello: 'recast' };
}
`
var recast = require('./main.js');

recast.parse(code)

```

```
/Users/noyobo/home/github/recast/node_modules/.npminstall/esprima/2.7.2/esprima/esprima.js:5701
            throw e;
            ^
Error: Line 3: Unexpected token =
    at constructError (/Users/noyobo/home/github/recast/node_modules/.npminstall/esprima/2.7.2/esprima/esprima.js:2406:21)
    at createError (/Users/noyobo/home/github/recast/node_modules/.npminstall/esprima/2.7.2/esprima/esprima.js:2425:17)
    at unexpectedTokenError (/Users/noyobo/home/github/recast/node_modules/.npminstall/esprima/2.7.2/esprima/esprima.js:2499:13)
    at throwUnexpectedToken (/Users/noyobo/home/github/recast/node_modules/.npminstall/esprima/2.7.2/esprima/esprima.js:2504:15)
    at parseClassBody (/Users/noyobo/home/github/recast/node_modules/.npminstall/esprima/2.7.2/esprima/esprima.js:5146:21)
    at parseClassDeclaration (/Users/noyobo/home/github/recast/node_modules/.npminstall/esprima/2.7.2/esprima/esprima.js:5168:21)
    at parseStatementListItem (/Users/noyobo/home/github/recast/node_modules/.npminstall/esprima/2.7.2/esprima/esprima.js:3980:24)
    at parseScriptBody (/Users/noyobo/home/github/recast/node_modules/.npminstall/esprima/2.7.2/esprima/esprima.js:5489:25)
    at parseProgram (/Users/noyobo/home/github/recast/node_modules/.npminstall/esprima/2.7.2/esprima/esprima.js:5505:16)
    at Object.parse (/Users/noyobo/home/github/recast/node_modules/.npminstall/esprima/2.7.2/esprima/esprima.js:5689:23)
```

https://github.com/benjamn/recast/issues/188

**Comment by hzoo** [comment]
It's because you are using esprima which doesn't support the experimental feature (you need to use the babylon parser)
