### ISSUE TITLE
recast.print: modifying a trailing CommentBlock when returning an identifier leads to assertion error

### ISSUE THREAD

**Issue by drifkin** [benjamn/recast#391]
I think I've got it down to a fairly minimal test case.

Running the following code...

```javascript
'use strict';

const recast = require('recast');

const ast = recast.parse(`function a() {
  return x/*comment*/;
}`);

recast.types.visit(ast, {
  visitComment: function (path) {
    path.value.value = path.value.value.replace('comment', 'COMMENT');
    this.traverse(path);
  }
});

console.log(recast.print(ast).code);
```

leads to this assertion error:

```
AssertionError: false == true
    at pushSlice (./node_modules/recast/lib/patcher.js:47:14)
    at Patcher.self.get (./node_modules/recast/lib/patcher.js:63:5)
    at ./node_modules/recast/lib/patcher.js:218:20
    at maybeReprint (./node_modules/recast/lib/printer.js:95:41)
    at print (./node_modules/recast/lib/printer.js:75:29)
    at exports.printComments (./node_modules/recast/lib/comments.js:325:22)
    at printWithComments (./node_modules/recast/lib/printer.js:61:16)
    at FastPath.call (./node_modules/recast/lib/fast-path.js:119:16)
    at genericPrintNoParens (./node_modules/recast/lib/printer.js:573:33)
    at genericPrint (./node_modules/recast/lib/printer.js:164:9)
```

If I don't modify the comment, things are fine since it doesn't try to reprint it. If the semi-colon is placed before the comment, it will also work.

**Comment by drifkin** [comment]
I suspect this is related to #364. I tried running this on v0.11.21 and it worked, but on v0.11.22 the assertion started.
