### ISSUE TITLE
Cannot parse a string with escape characters

### ISSUE THREAD

**Issue by ginqi7** [benjamn/recast#421]
When I try to use recast to parse a string with escape characters, it throw a error.
Example:
``` js
var source = "var str = 'hello\nworld';";
var tree = recast.parse(source);
```
There are an error like this:
```
/node_modules/esprima/dist/esprima.js:5027
	        throw this.createError(index, line, col, description);
Error: Line 1: Unexpected token ILLEGAL
at ErrorHandler.constructError (/node_modules/esprima/dist/esprima.js:5004:22)
    at ErrorHandler.createError (/node_modules/esprima/dist/esprima.js:5020:27)
    at ErrorHandler.throwError (/node_modules/esprima/dist/esprima.js:5027:21)
    at Scanner.throwUnexpectedToken (/node_modules/esprima/dist/esprima.js:5155:35)
    at Scanner.scanStringLiteral (/node_modules/esprima/dist/esprima.js:5929:19)
    at Scanner.lex (/node_modules/esprima/dist/esprima.js:6231:26)
    at JSXParser.Parser.nextToken (/node_modules/esprima/dist/esprima.js:2079:34)
    at JSXParser.Parser.parseVariableDeclaration (/node_modules/esprima/dist/esprima.js:3604:19)
    at JSXParser.Parser.parseVariableDeclarationList (/node_modules/esprima/dist/esprima.js:3615:25)
    at JSXParser.Parser.parseVariableStatement (/node_modules/esprima/dist/esprima.js:3625:34)
````

**Comment by benjamn** [comment]
The source string you're creating is not valid JavaScript code:
```js
var str = 'hello
world';
```
If you want to create a string of code that contains a string literal that contains a newline, you need to escape it with an extra `\`:
```js
var source = "var str = 'hello\\nworld';";
```

**Comment by ginqi7** [comment]
I realized that I was wrong.
Thank you.
