### ISSUE TITLE
gulp compile error (node: v7.10.1 npm: v4.2.0 MAC)

### ISSUE THREAD

**Issue by motiveYW** [benjamn/recast#445]
/node_modules/recast/node_modules/esprima-fb/esprima.js:7736
            throw e;
            ^

Error: Line 6: Unexpected token if
    at throwError (/Users/wy/HYQ/hyq-mobile-frontend/node_modules/recast/node_modules/esprima-fb/esprima.js:2819:21)
    at throwUnexpected (/Users/wy/HYQ/hyq-mobile-frontend/node_modules/recast/node_modules/esprima-fb/esprima.js:2873:13)
    at parseVariableIdentifier (/Users/wy/HYQ/hyq-mobile-frontend/node_modules/recast/node_modules/esprima-fb/esprima.js:4780:13)
    at parseTypeAnnotatableIdentifier (/Users/wy/HYQ/hyq-mobile-frontend/node_modules/recast/node_modules/esprima-fb/esprima.js:4788:21)
    at parseVariableDeclaration (/Users/wy/HYQ/hyq-mobile-frontend/node_modules/recast/node_modules/esprima-fb/esprima.js:4830:68)
    at parseVariableDeclarationList (/Users/wy/HYQ/hyq-mobile-frontend/node_modules/recast/node_modules/esprima-fb/esprima.js:4855:23)
    at parseVariableStatement (/Users/wy/HYQ/hyq-mobile-frontend/node_modules/recast/node_modules/esprima-fb/esprima.js:4870:24)
    at parseStatement (/Users/wy/HYQ/hyq-mobile-frontend/node_modules/recast/node_modules/esprima-fb/esprima.js:5698:24)
    at parseSourceElement (/Users/wy/HYQ/hyq-mobile-frontend/node_modules/recast/node_modules/esprima-fb/esprima.js:6454:24)
    at parseFunctionSourceElements (/Users/wy/HYQ/hyq-mobile-frontend/node_modules/recast/node_modules/esprima-fb/esprima.js:5791:29)

**Comment by benjamn** [comment]
You'll have to provide more information than this! The `esprima-fb` parser is throwing a parse error, so (at the very least) it would help to know what code it was trying to parse.

**Comment by benjamn** [comment]
Closing since we haven't heard back with any additional details in a few months.
