### ISSUE TITLE
v0.13.1 broke printing mutations of numeric literals

### ISSUE THREAD

**Issue by eventualbuddha** [benjamn/recast#469]
Simple reproduction:

```js
const recast = require('./');
const assert = require('assert');

const code = '3 + 4;';
const ast = recast.parse(code);
const { left, right } = ast.program.body[0].expression;

left.value++;
right.value++;

assert.strictEqual(recast.print(ast).code, '4 + 5;');
console.log('all good!');
```

In recast v0.13.0:

```sh
$ node bug.js
all good!
```

In recast v0.13.1:

```sh
$ node bug.js
assert.js:42
  throw new errors.AssertionError({
  ^

AssertionError [ERR_ASSERTION]: '3 + 4;' === '4 + 5;'
    at Object.<anonymous> (/Users/donovan/lib/recast/bug.js:11:8)
    at Module._compile (module.js:641:30)
    at Object.Module._extensions..js (module.js:652:10)
    at Module.load (module.js:560:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Function.Module.runMain (module.js:682:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:613:3
```

This is blocking babel-codemod from updating to v0.13.1.

**Comment by benjamn** [comment]
This should be fixed in `recast@0.13.2`!
