### ISSUE TITLE
`parser.parse` function throws error on template literals

### ISSUE THREAD

**Issue by dy** [benjamn/recast#507]
```js
var esprima = require('esprima')
var recast = require('recast')
recast.parse('var a = ``', {
	parser: {
		parse: function (source) {
			return esprima.parse(source)
		}
	}
})
```

Throws error
```sh
C:\projects\ast-transform\node_modules\recast\lib\util.js:271
  var afterLeftBackTickPos = copyPos(node.loc.start);
                                              ^

TypeError: Cannot read property 'start' of undefined
    at fixTemplateLiteral (C:\projects\ast-transform\node_modules\recast\lib\util.js:271:47)
    at Object.util.fixFaultyLocations (C:\projects\ast-transform\node_modules\recast\lib\util.js:176:3)
    at TreeCopier.TCp.copy (C:\projects\ast-transform\node_modules\recast\lib\parser.js:133:8)
    at TreeCopier.TCp.copy (C:\projects\ast-transform\node_modules\recast\lib\parser.js:178:24)
    at TreeCopier.<anonymous> (C:\projects\ast-transform\node_modules\recast\lib\parser.js:124:22)
    at Array.forEach (<anonymous>)
    at TreeCopier.TCp.copy (C:\projects\ast-transform\node_modules\recast\lib\parser.js:123:10)
    at TreeCopier.TCp.copy (C:\projects\ast-transform\node_modules\recast\lib\parser.js:178:24)
    at TreeCopier.<anonymous> (C:\projects\ast-transform\node_modules\recast\lib\parser.js:124:22)
    at Array.forEach (<anonymous>)
npm ERR! Test failed.  See above for more details.
```

Due to that it is impossible to use jsx-enabled esprima for now.

**Comment by cspotcode** [comment]
I think you need to do this:

```
esprima.parse(source, {loc: true, range: true})
```

Esprima doesn't set node location information by default, but it's required for recast.

**Comment by dy** [comment]
@cspotcode thanks, will check now. I tried to specifically enable `jsx` for `esprima` as
```js
var esprima = require('esprima')
var recast = require('recast')
recast.parse('var a = ``', {
	parser: {
		parse: function (source) {
			return esprima.parse(source, {jsx: true})
		}
	}
})
```

**Comment by dy** [comment]
Yep, works. Thanks!
