### ISSUE TITLE
Trailing comma in destructuring rest spread property breaks code

### ISSUE THREAD

**Issue by coderaiser** [benjamn/recast#559]
When `print` option `trailingComma` used, and one of nodes in object destructuring removed, trailing comma added to spread operator which leads to broken code:

```js
const { ...b,} = obj
           ^

SyntaxError: Rest element must be last element
```

Code to reproduce:

```js
const babel = require('@babel/parser');
const traverse = require('@babel/traverse').default;
const generate = require('@babel/generator').default;
const recast = require('recast');

const source = `
    const {
        a,
        ...b
    } = obj;
`;

const babelAST = recast.parse(source, {
    parser: {
        parse: babel.parse,
    }
});

let once = false;
traverse(babelAST, {
    enter(path) {
        if (once)
            return;

        if (path.type !== 'ObjectProperty')
            return;

        path.remove();
        once = true;
    }
});

console.log(recast.print(babelAST, {
    trailingComma: true,
}));
// outputs
// PrintResult { code: '\n    const {\n        ...b,\n    } = obj;\n' }
```
Will be great to not add comma when rest spread used :)

**Comment by krzysztofpniak** [comment]
Where did you get that syntax error?

**Comment by coderaiser** [comment]
Change `console.log` to `eval`:

```js
const babel = require('@babel/parser');
const traverse = require('@babel/traverse').default;
const generate = require('@babel/generator').default;
const recast = require('recast');

const source = `
    const {
        a,
        ...b
    } = obj;
`;

const babelAST = recast.parse(source, {
    parser: {
        parse: babel.parse,
    }
});

let once = false;
traverse(babelAST, {
    enter(path) {
        if (once)
            return;

        if (path.type !== 'ObjectProperty')
            return;

        path.remove();
        once = true;
    }
});

eval(recast.print(babelAST, {
    trailingComma: true,
}).code);
```

And you will see and error:

```js
undefined:3
        ...b,
           ^

SyntaxError: Rest element must be last element
    at Object.<anonymous> (/home/coderaiser/semicolon.js:39:3)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
```

**Comment by Daniel15** [comment]
https://github.com/benjamn/recast/pull/716 should fix this.
