### ISSUE TITLE
Parsing with `babel-parser` when on >= v0.16.0 breaks JSX parsing

### ISSUE THREAD

**Issue by mrcthms** [benjamn/recast#573]
Hi there!

Firstly, I just want to say thank you for the library, it’s great! I've noticed something funky going on when using the `@babel/parser` custom parser with `recast@>=0.16.0`.

With the following code, I get an error:

```js
const recast = require("recast");
const babelParser = require("@babel/parser");

const parser = {
  parse(code) {
    return babelParser.parse(code, {
      sourceType: "module",
      plugins: ["jsx"]
    });
  }
};

const parse = contents => {
  const ast = recast.parse(contents, { parser });
  return ast;
};

function init() {
  const code = `import React from 'react'
const Component = () => (
  <div>Hello, World</div>
)
`;
  const result = parse(code);
  console.log(result);
}

init();
```

The error is as follows:

```
Error: Line 3: Invalid regular expression: missing /
    at ErrorHandler.constructError (/Users/marc/Sites/code/babel-parser-issue/node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (/Users/marc/Sites/code/babel-parser-issue/node_modules/esprima/dist/esprima.js:5028:27)
    at ErrorHandler.throwError (/Users/marc/Sites/code/babel-parser-issue/node_modules/esprima/dist/esprima.js:5035:21)
    at Scanner.throwUnexpectedToken (/Users/marc/Sites/code/babel-parser-issue/node_modules/esprima/dist/esprima.js:5164:35)
    at Scanner.scanRegExpBody (/Users/marc/Sites/code/babel-parser-issue/node_modules/esprima/dist/esprima.js:6139:23)
    at Scanner.scanRegExp (/Users/marc/Sites/code/babel-parser-issue/node_modules/esprima/dist/esprima.js:6204:29)
    at Tokenizer.getNextToken (/Users/marc/Sites/code/babel-parser-issue/node_modules/esprima/dist/esprima.js:6675:56)
    at Object.tokenize (/Users/marc/Sites/code/babel-parser-issue/node_modules/esprima/dist/esprima.js:154:36)
    at Object.parse (/Users/marc/Sites/code/babel-parser-issue/node_modules/recast/lib/parser.js:48:30)
    at parse (/Users/marc/Sites/code/babel-parser-issue/index.js:14:22)
```

It seems all other plugins work, just the `jsx` plugin that fails. If I revert `recast` back to `0.15.5` then it works as intended.

I checked just parsing via `@babel/parser` directly to make sure it wasn't an error their end, and that worked as intended, too.

I've uploaded a test repo at https://github.com/mrcthms/babel-parser-jsx-issue/blob/master/index.js

Let me know if you need any other information!

Thanks!

**Comment by bnjmnt4n** [comment]
Hi @mrcthms! Recast sends some custom options, like [`tokens`](https://github.com/benjamn/recast/blob/09b5fa71f595e9289079ec163c5000aad92d332d/lib/parser.ts#L36-L44) to Babel and other parsers in order to allow for better printing/re-printing of nodes. Hence, we recommend using our pre-configured parsers (`const babel7 = require('recast/parsers/babel')`) to allow Recast to function properly.

**Comment by mrcthms** [comment]
@bnjmnt4n thanks for that, that's worked a treat. Will close!

**Comment by Smolations** [comment]
@mrcthms This would be especially useful in the documentation somewhere. I spent a couple hours trying to track this issue down, hacking my esprima dist locally to get it working with native babel stuff. Please and thank you!  😁

**Comment by eventualbuddha** [comment]
@Smolations some docs would be a good idea, if you’re up for a PR. Related, I created another package called [`@codemod/parser`](https://www.npmjs.com/package/@codemod/parser) whose purpose is to parse everything Babel is capable of parsing by e.g. enabling all plugins etc. It’s used as recast’s parser in [`@codemod/cli`](https://www.npmjs.com/package/@codemod/cli).
