### ISSUE TITLE
... operator for json will throw an exception

### ISSUE THREAD

**Issue by theajack** [benjamn/recast#620]
`var x={...{xx:1}}`

Error: Line 10: Unexpected token ...
    at ErrorHandler.constructError (F:\theajack\tcon\node_modules\esprima\dist\esprima.js:5012:22)
    at ErrorHandler.createError (F:\theajack\tcon\node_modules\esprima\dist\esprima.js:5028:27)
    at Parser.unexpectedTokenError (F:\theajack\tcon\node_modules\esprima\dist\esprima.js:1985:39)

**Comment by LeoEatle** [comment]
use `acorn` instead of `esprima`

**Comment by BillyRayPreachersSon** [comment]
This worked for me:

- Adding a dev dependency for `@babel/parser` to your `package.json` (e.g. `"@babel/parser": "^7.9.4"`)

- Requiring babel as well as recast
```
const babel = require('@babel/parser');
const recast = require('recast');
```

- Specifying the babel parser as an option
```
const ast = recast.parse(fileText, { parser: { parse: babel.parse } });
```

**Comment by benjamn** [comment]
A slightly better strategy:
```js
const ast = recast.parse(fileText, {
  parser: require("recast/parsers/babel"),
});
```
This will ensure reasonable default options are configured. Note that installing `@babel/parser` as a dev dependency is still important, so that it can be imported by the `recast/parsers/babel` module.

**Comment by coxmi** [comment]
Sorry to dredge through an old thread, but I'm facing the same issue.

`const { ...props } = obj` generates an `Unexpected token ...` error. 

Acorn doesn't choke on it normally, but does when it's run through recast.
`@babel/parser` and `recast/parsers/babel` don't produce the same error, but fail anyway with:

```
TypeError: baseVisitor[type] is not a function
```

Any ideas on how to get around this?
Thanks!

**Comment by theRizwan** [comment]
This has two separate causes, which is probably why it has stayed open so long.

The example with no parser option goes through esprima, and esprima 4.0.1 cannot parse object spread at any setting. I checked with `ecmaVersion: 2018`, `ecmaVersion: 2020` and `tolerant: true`, and it throws `Line 1: Unexpected token ...` every time. Nothing in recast can fix that one, the parser just does not support the syntax.

The acorn example is a recast bug though. `lib/parser.ts` passes a hardcoded `ecmaVersion: 6` to whatever parser it is handed, and that overrides the value `parsers/acorn.ts` asks for, so the acorn parser shown in the README cannot parse anything newer than ES6. Object spread, object rest, `**`, async and await, and optional catch binding all throw. I have opened #1441 for that half.

So this issue would stay open for the esprima half after that lands, unless you would rather close it and point people at `parsers/babel`, which is what you suggested earlier in the thread.
