### ISSUE TITLE
Is it possible to support vue template parsing?

### ISSUE THREAD

**Issue by zicjin** [benjamn/recast#842]
```
const parser = require("@vue/compiler-sfc")
const result = parser.parse(content)

if (result.errors.length) {
  throw result.errors
}

const { template, script, styles } = result.descriptor
const acornAst = recast.parse(template.ast, {
  parser: parser
});
```
got the error:
```
node_modules\esprima\dist\esprima.js:5008
                    throw error;
                    ^
Error: Line 1: Invalid regular expression: missing /
    at ErrorHandler.constructError (node_modules\esprima\dist\esprima.js:5012:22)
    at ErrorHandler.createError (node_modules\esprima\dist\esprima.js:5028:27)
    at ErrorHandler.throwError (node_modules\esprima\dist\esprima.js:5035:21)
    at Scanner.throwUnexpectedToken (node_modules\esprima\dist\esprima.js:5164:35)
    at Scanner.scanRegExpBody (node_modules\esprima\dist\esprima.js:6157:19)
    at Scanner.scanRegExp (node_modules\esprima\dist\esprima.js:6204:29)
    at Tokenizer.getNextToken (node_modules\esprima\dist\esprima.js:6675:56)
    at Object.tokenize (node_modules\esprima\dist\esprima.js:154:36)
    at Object.parse (node_modules\recast\lib\parser.js:40:30)
    at compiler (compiler.js:32:27) {
  index: 14,
  lineNumber: 1,
  description: 'Invalid regular expression: missing /'
}
```

**Comment by eventualbuddha** [comment]
> ```js
> const recast = require("recast")
> const parser = require("@vue/compiler-sfc")
> 
> const result = parser.parse(content)
> 
> if (result.errors.length) {
>   throw result.errors
> }
> 
> const { template, script, styles } = result.descriptor
> const acornAst = recast.parse(template.ast, {
>   parser: parser
> });
> ```

This doesn't look like the right way to parse. Maybe just do `recast.parse(content, { parser: parser })`?

**Comment by zicjin** [comment]
@eventualbuddha you are right, It is my mistake, but using @vue/compiler-sfc as a parser is still fail.
```
  const acornAst = recast.parse(content, {
    parser: require("@vue/compiler-sfc")
  });
  const output = recast.print(acornAst)
```
got the error:
```
node_modules\esprima\dist\esprima.js:5008
                    throw error;
                    ^
Error: Line 2: Invalid regular expression: missing /
    at ErrorHandler.constructError (node_modules\esprima\dist\esprima.js:5012:22)
    at ErrorHandler.createError (node_modules\esprima\dist\esprima.js:5028:27)
    at ErrorHandler.throwError (node_modules\esprima\dist\esprima.js:5035:21)
    at Scanner.throwUnexpectedToken (node_modules\esprima\dist\esprima.js:5164:35)
    at Scanner.scanRegExpBody (node_modules\esprima\dist\esprima.js:6139:23)
    at Scanner.scanRegExp (node_modules\esprima\dist\esprima.js:6204:29)
    at Tokenizer.getNextToken (node_modules\esprima\dist\esprima.js:6675:56)
    at Object.tokenize (node_modules\esprima\dist\esprima.js:154:36)
    at Object.parse (node_modules\recast\lib\parser.js:40:30)
    at compiler (compiler.js:33:27) {
  index: 33,
  lineNumber: 2,
  description: 'Invalid regular expression: missing /'
}
```

**Comment by AurelienLourot** [comment]
Any news on this? Simple reproducer:

```js
import { parse } from "recast";
import parser from "@vue/compiler-sfc";

const content = `
<template>
  <div>
    <h1>Hello World!</h1>
  </div>
</template>
`;

const result = parse(content, { parser });
```

```
node:internal/process/esm_loader:97
    internalBinding('errors').triggerUncaughtException(
                              ^
Error: Line 4: Invalid regular expression: missing /
    at ErrorHandler.constructError (.../node_modules/esprima/dist/esprima.js:5012:22)
    at ErrorHandler.createError (.../node_modules/esprima/dist/esprima.js:5028:27)
    at ErrorHandler.throwError (.../node_modules/esprima/dist/esprima.js:5035:21)
    at Scanner.throwUnexpectedToken (.../node_modules/esprima/dist/esprima.js:5164:35)
    at Scanner.scanRegExpBody (.../node_modules/esprima/dist/esprima.js:6139:23)
    at Scanner.scanRegExp (.../node_modules/esprima/dist/esprima.js:6204:29)
    at Tokenizer.getNextToken (.../node_modules/esprima/dist/esprima.js:6675:56)
    at Object.tokenize (.../node_modules/esprima/dist/esprima.js:154:36)
    at parse (.../node_modules/recast/lib/parser.js:40:30)
    at file://.../myscript.mjs:18:16 {
  index: 46,
  lineNumber: 4,
  description: 'Invalid regular expression: missing /'
}

Node.js v18.17.0
```

Thanks!
