### ISSUE TITLE
AssertionError in patcher when multiple versions of recast are used

### ISSUE THREAD

**Issue by ruslankhh** [benjamn/recast#843]
Hi! Thank you for your project.

I have a problem. 
```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert_1.default.ok(lines instanceof linesModule.Lines)

    at new Patcher (/path_to_my_package/node_modules/recast/lib/patcher.js:20:22)
    at /path_to_my_package/node_modules/recast/lib/patcher.js:138:23
    at print (/path_to_my_package/node_modules/recast/lib/printer.js:76:17)
    at /path_to_my_package/node_modules/recast/lib/printer.js:49:41
    at Object.printComments (/path_to_my_package/node_modules/recast/lib/comments.js:281:22)
    at print (/path_to_my_package/node_modules/recast/lib/printer.js:55:31)
    at Printer.print (/path_to_my_package/node_modules/recast/lib/printer.js:88:21)
    at Object.print (/path_to_my_package/node_modules/recast/main.js:31:43)
    at Collection.toSource (/path_to_my_package/node_modules/jscodeshift/src/Collection.js:178:21)
    at astGetParsedValue (/path_to_my_package/build/src/test-spec-collection/test-spec-hermione.js:121:52)
    at traverse (/path_to_my_package/build/src/test-spec-collection/test-spec-hermione.js:93:43)
    at astGetFullTitle (/path_to_my_package/build/src/test-spec-collection/test-spec-hermione.js:101:5)
    at NodePath.<anonymous> (/path_to_my_package/build/src/test-spec-collection/test-spec-hermione.js:61:30)
    at /path_to_my_project/node_modules/jscodeshift/src/Collection.js:75:36
    at Array.forEach (<anonymous>)
    at Collection.forEach (/path_to_my_project/node_modules/jscodeshift/src/Collection.js:74:18)
    at Object.getTestSpecFromHermioneAst (/path_to_my_package/build/src/test-spec-collection/test-spec-hermione.js:60:10)
    at TestSpecCollection.<anonymous> (/path_to_my_package/build/src/test-spec-collection/index.js:33:62)
    at /path_to_my_package/build/src/test-spec-collection/index.js:53:85
    at Set.forEach (<anonymous>)
    at TestSpecCollection.addTestSpec (/path_to_my_package/build/src/test-spec-collection/index.js:50:20)
    at /path_to_my_package/build/src/index.js:44:68 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
```

I'm using a [jscodeshift](https://github.com/facebook/jscodeshift) that uses recast.
I use this in several of my packages that work with each other in many ours inner projects.
And I get an error for example in this pseudo code:

```js

// package-1/index.js
const j = require('jscodeshift');

module.exports = (code) => j(code).findSomeNode();

// package-2/index.js
const j = require('jscodeshift');
const getAstNode = require('package-1');

const someNode = getAstNode('some-code');

// AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value
const result = j(node).modifySomeNode().toSource();
```

The error occurs in these places:
https://github.com/facebook/jscodeshift/blob/master/src/Collection.js#L178
https://github.com/benjamn/recast/blob/master/lib/patcher.ts#L28
Because the class `linesModule.Lines` is taken from different versions of recast.

I found the advice here:
https://github.com/benjamn/recast/pull/645#issuecomment-542932020
But it doesn't suit us. We use npm (there are many reasons to use it, we can't abandon it), and there are too many packages and projects to be able to reconcile this and maintain it.

Maybe you can do a friendlier check and add a bit of polymorphism?

Thanks.

**Comment by eventualbuddha** [comment]
One approach would be to provide the `jscodeshift` dependency to `package-1`:

```js
// package-1/index.js
const jscodeshift = require('jscodeshift');

module.exports = (code, j = jscodeshift) => j(code).findSomeNode();

// package-2/index.js
const j = require('jscodeshift');
const getAstNode = require('package-1');

const someNode = getAstNode('some-code', j);

// AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value
const result = j(node).modifySomeNode().toSource();
```

I believe that would work around the issue you're seeing.

As to whether the `instanceof` check warrants changing… I don't know. I tend to avoid such things in my JS packages for reasons like this, but this is a larger change than I'd feel comfortable making without buy-in from @benjamn.

**Comment by ruslankhh** [comment]
Thank you for your time.
I'll do something like that. This is not very convenient. I hope someone else will change your mind.
